# permissions for end users to view klustertraffics.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: klustertraffic-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kluster-traffic-operator
    app.kubernetes.io/part-of: kluster-traffic-operator
    app.kubernetes.io/managed-by: kustomize
  name: klustertraffic-viewer-role
rules:
- apiGroups:
  - operators.jubril.xyz
  resources:
  - klustertraffics
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - operators.jubril.xyz
  resources:
  - klustertraffics/status
  verbs:
  - get
